return {
  {
    "nvim-telescope/telescope.nvim",
    opts = {
      defaults = {
        vimgrep_arguments = {
          "rg",
          "--color=never",
          "--no-heading",
          "--with-filename",
          "--line-number",
          "--column",
          "--smart-case",
          "--hidden",
          "--no-ignore",
          "-g",
          "!**/.git/*",
          "-g",
          "!**/.idea/*",
          "-g",
          "!**/.vscode/*",
          "-g",
          "!**/build/*",
          "-g",
          "!**/vendor/*",
          "-g",
          "!**/dist/*",
          "-g",
          "!**/yarn.lock",
          "-g",
          "!**/package-lock.json",
          "-g",
          "!**/node_modules/*",
          "-g",
          "!**/bladecache/*",
          "-g",
          "!**/composer.lock",
          "-g",
          "!.docker/init.sql",
        },
      },
      pickers = {
        find_files = {
          hidden = true,
          find_command = {
            "rg",
            "--files",
            "--hidden",
            "--no-ignore",
            "--glob=!**/.git/*",
            "--glob=!**/.idea/*",
            "--glob=!**/.vscode/*",
            "--glob=!**/build/*",
            "--glob=!**/vendor/*",
            "--glob=!**/dist/*",
            "--glob=!**/yarn.lock",
            "--glob=!**/package-lock.json",
            "--glob=!**/node_modules/*",
          },
        },
      },
    },
  },
}
